spring.application.name=TravelAdvisor
spring.ai.openai.api-key=${OPENAI_API_KEY}

weather.api.provider=openweathermap
weather.api.key=bba8836837dd6c6b1a2a2e2095c466b6
weather.api.baseUrl=https://api.openweathermap.org/data/2.5

#https://api.openweathermap.org/data/2.5/weather?q={city name}&appid={API key}